export const trending = [
  {
    id: "1",
    title: "Viral clip claims new lunar base discovered on far side of the Moon",
    category: "Science",
    verdict: "False",
    score: 12,
    sources: 14,
    region: "Global",
  },
  {
    id: "2",
    title: "AI-generated voice impersonates finance minister announcing rate cut",
    category: "Finance",
    verdict: "Manipulated",
    score: 8,
    sources: 22,
    region: "EU",
  },
  {
    id: "3",
    title: "Photo of flooded stadium re-shared from 2019 event as current",
    category: "World",
    verdict: "Out of Context",
    score: 31,
    sources: 9,
    region: "South Asia",
  },
  {
    id: "4",
    title: "Deepfake video of athlete endorsing crypto token spreads on X",
    category: "Sports",
    verdict: "AI Generated",
    score: 6,
    sources: 18,
    region: "North America",
  },
];

export const verifiedFeed = [
  {
    id: "v1",
    title: "Independent agencies confirm new vaccine trial Phase III results",
    source: "Reuters",
    category: "Health",
    trust: 96,
    verdict: "True",
    time: "2h ago",
  },
  {
    id: "v2",
    title: "Senate committee releases full transcript of cybersecurity hearing",
    source: "AP News",
    category: "Politics",
    trust: 94,
    verdict: "True",
    time: "4h ago",
  },
  {
    id: "v3",
    title: "ESA confirms successful docking of resupply mission",
    source: "BBC",
    category: "Science",
    trust: 95,
    verdict: "True",
    time: "6h ago",
  },
  {
    id: "v4",
    title: "Quarterly inflation figures revised downward by national bureau",
    source: "The Hindu",
    category: "Finance",
    trust: 92,
    verdict: "Mostly True",
    time: "8h ago",
  },
  {
    id: "v5",
    title: "Climate report links extreme heat events to long-term warming trend",
    source: "Nature",
    category: "Science",
    trust: 97,
    verdict: "True",
    time: "12h ago",
  },
  {
    id: "v6",
    title: "Trade ministers conclude negotiations on regional digital framework",
    source: "Reuters",
    category: "World",
    trust: 95,
    verdict: "True",
    time: "1d ago",
  },
];

export const sources = [
  { name: "Reuters", trust: 98, articles: 12480, type: "Wire" },
  { name: "BBC", trust: 96, articles: 9870, type: "Broadcast" },
  { name: "AP News", trust: 95, articles: 11320, type: "Wire" },
  { name: "The Hindu", trust: 95, articles: 6210, type: "Newspaper" },
  { name: "Nature", trust: 97, articles: 1420, type: "Journal" },
  { name: "WHO", trust: 99, articles: 980, type: "Institution" },
  { name: "NASA", trust: 99, articles: 1120, type: "Institution" },
  { name: "CNN", trust: 90, articles: 8740, type: "Broadcast" },
  { name: "The Guardian", trust: 91, articles: 7320, type: "Newspaper" },
  { name: "Bloomberg", trust: 92, articles: 9020, type: "Wire" },
  { name: "Buzzy Daily", trust: 38, articles: 2310, type: "Blog" },
  { name: "TruthLeaks247", trust: 21, articles: 1840, type: "Blog" },
];

export const claims = [
  {
    id: "c1",
    text: "The new vaccine has shown 92% efficacy in Phase III trials.",
    verdict: "verified" as const,
    note: "Confirmed by 4 independent sources including WHO bulletin.",
    sources: ["WHO", "Nature", "Reuters"],
  },
  {
    id: "c2",
    text: "The trial was completed in under three weeks.",
    verdict: "false" as const,
    note: "Trial spanned 14 months across 6 countries per published protocol.",
    sources: ["Nature", "FDA"],
  },
  {
    id: "c3",
    text: "Side effects were reported in less than 1% of participants.",
    verdict: "context" as const,
    note: "Severe side effects <1%; mild reactions ~22%. Headline omits context.",
    sources: ["Lancet"],
  },
  {
    id: "c4",
    text: "Distribution will begin globally within the next quarter.",
    verdict: "opinion" as const,
    note: "Forward-looking statement from press briefing, not a confirmed timeline.",
    sources: ["Press release"],
  },
  {
    id: "c5",
    text: "Officials called the result 'a revolution that will end all disease'.",
    verdict: "ai" as const,
    note: "Quote matches synthetic voice patterns; no record of statement.",
    sources: ["Audio forensics"],
  },
];

export const agents = [
  { name: "Claim Extraction", status: "Done", ms: 420, icon: "Sparkles" },
  { name: "Evidence Search", status: "Done", ms: 1860, icon: "Search" },
  { name: "Fact Verification", status: "Done", ms: 980, icon: "ShieldCheck" },
  { name: "Bias Detection", status: "Done", ms: 310, icon: "Scale" },
  { name: "Emotion Detection", status: "Done", ms: 220, icon: "Activity" },
  { name: "Deepfake Detection", status: "Done", ms: 740, icon: "Eye" },
  { name: "Credibility Scoring", status: "Done", ms: 180, icon: "Gauge" },
  { name: "Report Generator", status: "Done", ms: 90, icon: "FileText" },
];
